All: s.cpp LibraryConversion.cpp InterfaceConversion.cpp LibraryCosinesLaw.cpp InterfaceCosinesLaw.cpp InterfaceSinesLaw.cpp LibrarySinesLaw.cpp LibraryRoot.cpp InterfaceRoot.cpp LibrarySumOfAngles.cpp InterfaceSumOfAngles.cpp LibraryDirectionFields.cpp InterfaceDirectionFields.cpp LibraryTrigArea.cpp InterfaceTrigArea.cpp LibrarySystemLinearEquations.cpp InterfaceSystemLinearEquations.cpp LibraryQuadraticEquation.cpp InterfaceQuadraticEquation.cpp InterfaceRecurrenceRelation.cpp LibraryRecurrenceRelation.cpp LibraryInterest.cpp InterfaceInterest.cpp LibraryGasLaws.cpp InterfaceGasLaws.cpp InterfaceChemistryConversion.cpp LibraryChemistryConversion.cpp LibraryChemistry.cpp InterfaceChemistry.cpp
	g++ s.cpp LibraryConversion.cpp InterfaceConversion.cpp LibraryCosinesLaw.cpp InterfaceCosinesLaw.cpp InterfaceSinesLaw.cpp LibrarySinesLaw.cpp LibraryRoot.cpp InterfaceRoot.cpp LibrarySumOfAngles.cpp InterfaceSumOfAngles.cpp LibraryDirectionFields.cpp InterfaceDirectionFields.cpp LibraryTrigArea.cpp InterfaceTrigArea.cpp LibrarySystemLinearEquations.cpp InterfaceSystemLinearEquations.cpp LibraryQuadraticEquation.cpp InterfaceQuadraticEquation.cpp InterfaceRecurrenceRelation.cpp LibraryRecurrenceRelation.cpp LibraryInterest.cpp InterfaceInterest.cpp LibraryGasLaws.cpp InterfaceGasLaws.cpp InterfaceChemistryConversion.cpp LibraryChemistryConversion.cpp LibraryChemistry.cpp InterfaceChemistry.cpp -std=c++11 -o 1

run:
	./1

clean:
	rm 1
	echo Clean done

show:
	pwd
	ls

