All: s.cpp LibraryQuadraticEquation.cpp InterfaceQuadraticEquation.cpp
	g++ s.cpp LibraryQuadraticEquation.cpp InterfaceQuadraticEquation.cpp -std=c++11 -o 1

run:
	./1

clean:
	rm 1
	echo Clean done

show:
	pwd
	ls

