All: s.cpp QuadraticEquation.cpp InterfaceRecurrenceRelation.cpp LibraryRecurrenceRelation.cpp SolveX.cpp
	g++ s.cpp QuadraticEquation.cpp InterfaceRecurrenceRelation.cpp LibraryRecurrenceRelation.cpp SolveX.cpp -std=c++11 -o 1

run:
	./1

clean:
	rm 1
	echo Clean done

show:
	pwd
	ls

