All: s.cpp LibrarySystemLinearEquations.cpp InterfaceSystemLinearEquations.cpp 
	g++ s.cpp LibrarySystemLinearEquations.cpp InterfaceSystemLinearEquations.cpp  -std=c++11 -o 1

run:
	./1

clean:
	rm 1
	echo Clean done

show:
	pwd
	ls

