All: s.cpp LibraryGasLaws.cpp InterfaceGasLaws.cpp InterfaceChemistryConversion.cpp LibraryChemistryConversion.cpp LibraryChemistry.cpp InterfaceChemistry.cpp
	g++ s.cpp LibraryGasLaws.cpp InterfaceGasLaws.cpp InterfaceChemistryConversion.cpp LibraryChemistryConversion.cpp LibraryChemistry.cpp InterfaceChemistry.cpp -std=c++11 -o 1

run:
	./1

clean:
	rm 1
	echo Clean done

show:
	pwd
	ls

